#!/bin/bash

DIRQL="/home/pi/qlauncher"
QLS="$DIRQL/qlauncher.sh"

function help ()
{
echo -e "\nUsage: Q [OPTION]...\n"
echo "Main Usage :"
echo "    -s, --s, -start, --start		start Qlauncher service"
echo "    -c, --c, -stop, --stop		stop Qlauncher service"
echo "    -r, --r, -restart, --restart	restart Qlauncher service"
echo "    -i, --i, -check, --check		check Qlauncher tick"
echo "    -l, --l, -status, --status		show status container"
echo "    -b, --b, -bind, --bind		get Qlauncher QR Code"
echo -e "\nMiscellaneous :"
echo "    -p, --p, -port, --port		check port status"
echo "    -d, --d, -rem, --rem		remove 'Exited' container"
echo "    -u, --u, -cpu, --cpu		show total cpu usage"
#echo "    -v, --v, -update, --update		update this script"
echo "    -n, --n, -hostname, --hostname	change hostname"
echo "    -w, --w, -about, --about		see magic"
echo
echo "Report this script to: <https://github.com/jakues/ql-rpi/issues>"
echo "Report Qlauncher bugs to: <https://github.com/poseidon-network/qlauncher-linux/issues>"
echo "Qlauncher github: <https://github.com/poseidon-network/qlauncher-linux>"
echo "Poseidon Network home page: <https://poseidon.network/>"
echo
}

function null ()
{
echo -e "\nUsage: Q [OPTION]...\n"
echo -e "Try 'Q --help' for more information.\n"
}

################
## main usage ##
################

function start ()
{
 if [[ ! $TRUE ]]
   then
      echo -e "\033[0;32m"
      sudo $QLS start > sudo /dev/null 2>&1 > sudo /var/log/Q &
      echo -n 'Starting Qlauncher ...  '
      PID=$!
      delay=${SPINNER_DELAY:-0.25}
      i=1
      sp="/-\|"
   while [ -d /proc/$PID ]
     do
        printf "\b${sp:i++%${#sp}:1}"
        sleep $delay
     done
        echo "OK !!!"
        clear
	echo -e "\033[0;33m"
     read -p "Are you want to check it ? [Y/y/N/n]" -n 1 -r
        echo -e "\033[0;37m"
   if [[ ! $REPLY =~ ^[Yy]$ ]]
     then
        exit 1
     else
	clear
        status | lolcat
   fi
 else
      echo -e "\n\033[0;31mQlauncher Already Running\033[0;37m\n"
      exit 1
 fi
}

function stop ()
{
 if [[ ! $TRUE ]]
   then
      exit 1
      echo -e "\n\033[0;31mQlauncher Not Running\033[0;37m\n"
 else
      echo -e "\033[0;31m"
      sudo $QLS stop > sudo /dev/null 2>&1 > sudo /var/log/Q &
      echo -n 'Stopping Qlauncher ...  '
      PID=$!
      delay=${SPINNER_DELAY:-0.25}
      i=1
      sp="/-\|"
   while [ -d /proc/$PID ]
     do
        printf "\b${sp:i++%${#sp}:1}"
        sleep $delay
     done
        echo "OK !!!"
        clear
	echo -e "\033[0;33m"
     read -p "Are you want to check it ? [Y/y/N/n]" -n 1 -r
        echo -e "\033[0;37m"
   if [[ ! $REPLY =~ ^[Yy]$ ]]
     then
        exit 1
     else
	clear
        check | lolcat
   fi
 fi
}

function restart ()
{
 echo -e "\033[0;32m"
 sudo $QLS restart > sudo /dev/null 2>&1 > sudo /var/log/Q &
 echo -n 'Restarting Qlauncher ...  '
   PID=$!
   delay=${SPINNER_DELAY:-0.25}
   i=1
   sp="/-\|"
 while [ -d /proc/$PID ]
   do
      printf "\b${sp:i++%${#sp}:1}"
      sleep $delay
   done
      sleep 5
      echo "OK !!!"
      clear
      echo -e "\033[0;33m"
      read -p "Are you want to check it ? [Y/y/N/n]" -n 1 -r
      echo -e "\033[0;37m"
 if [[ ! $REPLY =~ ^[Yy]$ ]]
   then
   exit 1
 else
   clear
   status | lolcat
 fi
}

function check ()
{
  echo
  sudo $QLS check
  echo
}

TRUE=$(check | grep '"edgecore_alive":"true"')

function status ()
{
  clear
  echo -e "\n\n"
  docker ps -a
  echo -e "\n"
}

function bind ()
{
  echo -e "\nPlease open this URL on your browser : \n"
  $QLS bind | cut -c 44-120
  echo
}

#################
##Miscellaneous##
#################

function port ()
{
   nmap -p 443,32440-32449 127.0.0.1
   echo
}

function rem ()
{
 echo -e "\n\033[1;31mRemoving 'Exited' Container ...\n"
 sleep 1
 docker rm $(docker ps -a -f status=exited -q)
 echo -e "\033[0;33m"
    read -p "Are you want to check it ? [Y/y/N/n]" -n 1 -r
 echo -e "\033[0;37m"
 if [[ ! $REPLY =~ ^[Yy]$ ]]
   then
     exit 1
 else
    clear
    status | lolcat
 fi
}

function cpu ()
{
 echo -e "\033[1;32m\nCpu Usage\n"
 awk '{u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else print ($2+$4-u1) * 100 / (t-t1) "%"; }' \
 <(grep 'cpu ' /proc/stat) <(sleep 1;grep 'cpu ' /proc/stat)
 echo -e "\033[0;37m"
}

function update ()
{
   apt-get update -y
   sudo curl -o /usr/local/bin/Q https://raw.githubusercontent.com/jakues/ql-rpi/master/conf/Q
   sudo chmod +x /usr/local/bin/Q
   clear
   about
}

function hostname ()
{
 if [ "$(id -u)" != "0" ] ; then
 	echo "Sorry, you are not root user"
 	exit
 fi
	read -r -p "Enter new hostname : " NEW_HOSTNAME
	echo
	CUR_HOSTNAME=$(cat /etc/hostname)
	echo "The current hostname is $CUR_HOSTNAME"
	echo
		hostnamectl set-hostname "${NEW_HOSTNAME}"
		sudo sed -i "s/$CUR_HOSTNAME/$NEW_HOSTNAME/g" /etc/hosts
		sudo sed -i "s/$CUR_HOSTNAME/$NEW_HOSTNAME/g" /etc/hostname
	echo
	echo "The new hostname is $NEW_HOSTNAME"
	echo
	read -p "Reboot now ? [Y/y/N/n]" -n 1 -r
 if [[ ! $REPLY =~ ^[Yy]$ ]]
   then
     exit 1
 else
     reboot
 fi
}

function about ()
{
 echo -e "\n\033[1;36m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\033[1;37m"
 echo -e "\033[1;36m@@\033[1;37mScript Auto Install Qlauncher-Lelenux\033[1;36m@@\033[1;37m"
 echo -e "\033[1;36m@@\033[1;37m	Original Script by Jakues™\033[1;36m     @@\033[1;37m"
 echo -e "\033[1;36m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\033[1;37m"
 echo -e "\nYou can donate me to address below\n\n"
 echo -e "\n\033[1;32mBTC:		bc1q8lshj8wxmf3cegvqc5atefy8q8pylmar5swxph\033[0;37m\n"
 echo -e "\n\033[1;32mERC20:		0x50D232369c7A4A77055ed129ee653bE18DFd78ab\033[0;37m\n"
 echo -e "\n\033[1;32mBNB:		bnb1v7np68j0mh4xg53rhyrze7shfkgj4tt8psyggk\033[0;37m\n"
 echo -e "\n\033[1;32mTRC20:		TQLcDqU7SC7PCdUtL5JmyTEzZx6Cq5tmdg\033[0;37m\n"
 echo
}

#################
###Buster Call###
#################

case "$1" in
 -s|--s|-start|--start)
start
;;
 -c|--c|-stop|--stop)
stop
;;
 -r|--r|-restart|--restart)
restart
;;
 -i|--i|-check|--check)
check | lolcat
;;
 -l|--l|-status|--status)
clear
status | lolcat
;;
 -b|--b|-bind|--bind)
bind | lolcat
;;
 -p|--p|-port|--port)
port | lolcat
;;
 -d|--d|-rem|--rem)
rem
;;
 -u|--u|-cpu|--cpu)
cpu
;;
 -v|--v|-update|--update)
update
;;
 -n|--n|-hostname|--hostname)
 hostname
;;
 -w|--w|-about|--about)
about
;;
 --help)
help | lolcat
;;
 *)
null | lolcat
;;
esac
